version: "3.9"
services:
  # react-app:
  #   container_name: wallaclone-frontend
  #   image: react-app
  #   restart: always
  #   stdin_open: true
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - wallaclone-app

  api-server:  
    container_name: api-server
    image: wallaclone-server #image generate dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - wallaclone-app
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - wallaclone-app
    volumes:
      - mongo-data:/data/db
  
networks:
  wallaclone-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
