version: "3.9"

services:
  
  #RabbitMQ services
  rabbitmq:
    container_name: wallaclone-queue-rabbit
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
     
  #MongoDB services
  mongodb:
    container_name: wallaclone-db-mongo
    restart: always
    image: mongo:latest
    volumes:
      - mongodb:/data/db

  #Node production app services
  api:
    container_name: wallaclone-apiproduction-node
    image: node:16.14-alpine3.15
    volumes:
      - ./:/app
    working_dir: /app
    restart: always
    command: npm start
    environment:
      - NODE_ENV=development
      - PORT=3000
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=gest
      - RABBIT_PASSWORD=gest
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    ports:
      - 80:3000
      
  #Node develop app services
  dev:
    container_name: wallaclone-apidevelop-node
    image: node:16.14-alpine3.15
    volumes:
      - ./:/app
    working_dir: /app
    restart: always
    command: npm start
    environment:
      - NODE_ENV=development
      - PORT=3000
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=gest
      - RABBIT_PASSWORD=gest
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017

volumes:
  mongodb: 


    


